services:
  - type: web
    name: smart-code-translator-api
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
